### PR TITLE
Adding --estimated option to create-issue command

### PR DESCRIPTION
**Pull request by pedrobaracho**
Adding "Estimated hours" option to the Create Issue command.

### CODE REVIEW

**Comment by a11n** [comment]
First of all, **many thanks** for contributing to this project! I really appreciate this!

Your PR looks **very nice**. However, to keep consistency, when adding an option to "create-issue" we should provide the same option for "update-issue" as well. Could you please also add the option and implementation for "update-issue"?

**Comment by pedrobaracho** [comment]
I'll work on that.

On a side note, I only implemented create-issue, because this was a spike to validate that it was possible to use redmine-cli to automate task generation. If you have some spare  time, you can [take a look at it](https://github.com/pedrobaracho/RedmineCLI/tree/generate-issues-command).

The usage is pretty simple: `$ redmine generate-issues <project> <model>`, where model is a predefined JSON imported via `$ redmine import-model <file-path> <model>`

**Comment by pedrobaracho** [comment]
I finished adding the option --estimated to update-issues as suggested.

**Comment by a11n** [comment]
Nice PR. Thank you.

**Pull request merged**
